export const countryCodes: { [key: string]: string } = {
    "Afganistán": "af", "Albania": "al", "Argelia": "dz", "Andorra": "ad", "Angola": "ao", "Antigua y Barbuda": "ag",
    "Argentina": "ar", "Armenia": "am", "Australia": "au", "Austria": "at", "Azerbaiyán": "az", "Bahamas": "bs",
    "Baréin": "bh", "Bangladés": "bd", "Barbados": "bb", "Bielorrusia": "by", "Bélgica": "be", "Belice": "bz",
    "Benín": "bj", "Bután": "bt", "Bolivia": "bo", "Bosnia y Herzegovina": "ba", "Botsuana": "bw", "Brasil": "br",
    "Brunéi": "bn", "Bulgaria": "bg", "Burkina Faso": "bf", "Burundi": "bi", "Cabo Verde": "cv", "Camboya": "kh",
    "Camerún": "cm", "Canadá": "ca", "República Centroafricana": "cf", "Chad": "td", "Chile": "cl", "China": "cn",
    "Colombia": "co", "Comoras": "km", "Congo": "cg", "Costa Rica": "cr", "Croacia": "hr", "Cuba": "cu", "Chipre": "cy",
    "República Checa": "cz", "Dinamarca": "dk", "Yibuti": "dj", "Dominica": "dm", "República Dominicana": "do",
    "Ecuador": "ec", "Egipto": "eg", "El Salvador": "sv", "Guinea Ecuatorial": "gq", "Eritrea": "er", "Estonia": "ee",
    "Esuatini": "sz", "Etiopía": "et", "Fiyi": "fj", "Finlandia": "fi", "Francia": "fr", "Gabón": "ga", "Gambia": "gm",
    "Georgia": "ge", "Alemania": "de", "Ghana": "gh", "Grecia": "gr", "Granada": "gd", "Guatemala": "gt", "Guinea": "gn",
    "Guinea-Bisáu": "gw", "Guyana": "gy", "Haití": "ht", "Honduras": "hn", "Hungría": "hu", "Islandia": "is", "India": "in",
    "Indonesia": "id", "Irán": "ir", "Irak": "iq", "Irlanda": "ie", "Israel": "il", "Italia": "it", "Costa de Marfil": "ci",
    "Jamaica": "jm", "Japón": "jp", "Jordania": "jo", "Kazajistán": "kz", "Kenia": "ke", "Kiribati": "ki", "Corea del Norte": "kp",
    "Corea del Sur": "kr", "Kuwait": "kw", "Kirguistán": "kg", "Laos": "la", "Letonia": "lv", "Líbano": "lb", "Lesoto": "ls",
    "Liberia": "lr", "Libia": "ly", "Liechtenstein": "li", "Lituania": "lt", "Luxemburgo": "lu", "Madagascar": "mg", "Malaui": "mw",
    "Malasia": "my", "Maldivas": "mv", "Malí": "ml", "Malta": "mt", "Islas Marshall": "mh", "Mauritania": "mr", "Mauricio": "mu",
    "México": "mx", "Micronesia": "fm", "Moldavia": "md", "Mónaco": "mc", "Mongolia": "mn", "Montenegro": "me", "Marruecos": "ma",
    "Mozambique": "mz", "Birmania": "mm", "Namibia": "na", "Nauru": "nr", "Nepal": "np", "Países Bajos": "nl", "Nueva Zelanda": "nz",
    "Nicaragua": "ni", "Níger": "ne", "Nigeria": "ng", "Noruega": "no", "Omán": "om", "Pakistán": "pk", "Palaos": "pw", "Panamá": "pa",
    "Papúa Nueva Guinea": "pg", "Paraguay": "py", "Perú": "pe", "Filipinas": "ph", "Polonia": "pl", "Portugal": "pt", "Catar": "qa",
    "Rumania": "ro", "Rusia": "ru", "Ruanda": "rw", "San Cristóbal y Nieves": "kn", "Santa Lucía": "lc", "San Vicente y las Granadinas": "vc",
    "Samoa": "ws", "San Marino": "sm", "Santo Tomé y Príncipe": "st", "Arabia Saudita": "sa", "Senegal": "sn", "Serbia": "rs", "Seychelles": "sc",
    "Sierra Leona": "sl", "Singapur": "sg", "Eslovaquia": "sk", "Eslovenia": "si", "Islas Salomón": "sb", "Somalia": "so", "Sudáfrica": "za",
    "Sudán del Sur": "ss", "España": "es", "Sri Lanka": "lk", "Sudán": "sd", "Surinam": "sr", "Suecia": "se", "Suiza": "ch", "Siria": "sy",
    "Tayikistán": "tj", "Tanzania": "tz", "Tailandia": "th", "Timor Oriental": "tl", "Togo": "tg", "Tonga": "to", "Trinidad y Tobago": "tt",
    "Túnez": "tn", "Turquía": "tr", "Turkmenistán": "tm", "Tuvalu": "tv", "Uganda": "ug", "Ucrania": "ua", "Emiratos Árabes Unidos": "ae",
    "Reino Unido": "gb", "Estados Unidos": "us", "Uruguay": "uy", "Uzbekistán": "uz", "Vanuatu": "vu", "Ciudad del Vaticano": "va",
    "Venezuela": "ve", "Vietnam": "vn", "Yemen": "ye", "Zambia": "zm", "Zimbabue": "zw",
    "Inglaterra": "gb", "Escocia": "gb", "Mexico": "mx","Holanda": "nl", "USA": "us", "United States": "us", "United Kingdom": "gb",
};
